//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pesticides.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ActiveIngredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActiveIngredient()
        {
            this.PesticidesInfoes = new HashSet<PesticidesInfo>();
        }
    
        public int ActiveIngredientPk { get; set; }
        [Display(Name ="المادة الفعالة باللغة العربية")]
        public string IngredientAr { get; set; }

        [Display(Name = "المادة الفعالة باللغة الإنكليزية")]
        public string IngredientEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PesticidesInfo> PesticidesInfoes { get; set; }
    }
}
